org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.160.0+26.2
owo_version=0.13.1+26.2
modmenu_version=20.0.2

mod_version=0.1.0
group=io.github.fivepebblesgpt
archives_base_name=elytraguides
